# Generated by Django 3.1.2 on 2020-10-26 20:43

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_rutag_rutaggeditem'),
        ('tasks', '0006_todoitem_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.RuTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
