# Generated by Django 3.1.2 on 2020-11-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20201026_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='trello_id_board',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
