# Generated by Django 3.1.2 on 2020-11-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_todoitem_trello_id_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='trello_id_card',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
